# Node.js  
# Build a general Node.js project with npm.  
# Add steps that analyze code, save build artifacts, deploy, and more:  
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript  
  
trigger:  
- develop  
  
pool:  
  vmImage: 'ubuntu-latest'  
  
steps:  
- task: NodeTool@0  
  inputs:  
    versionSpec: '16.x'  
  displayName: 'install Node.js 16.x'  
- task: Npm@1  
  displayName: 'install Angular CLI'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install @angular/cli@13.1.4'  
- task: Npm@1  
  displayName: 'npm install'  
  inputs:  
    verbose: false  
- task: Npm@1  
  displayName: npm tests  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'run test'  
- task: Npm@1  
  displayName: npm bulid  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'run build'  
  
- task: CopyPublishBuildArtifacts@1  
  displayName: 'Copy Publish Artifact: app'  
  inputs:  
    CopyRoot: dist  
    Contents: '**'  
    ArtifactName: app  
    ArtifactType: Container  
  
- task: DownloadPipelineArtifact@2  
  displayName: 'Download Pipeline Artifact'  
  inputs:  
    targetPath: ' $(Build.ArtifactStagingDirectory)/dist/clouddeveloperdesigner'  